version: '3'
services:
  app:
    container_name: portfolio-website
    restart: always
    build: .
    ports:
      - '1337:1337'
    links:
     - db
  db:
    container_name: portfolio-db
    image: mongo
    ports:
      - '27018:27017'
